### PR TITLE
Update FSharp.Compiler.Service to version 34.0.1

### PR DESCRIPTION
**Pull request by baronfel**
This brings along some perf improvements, as well as a slew of syntax features and preview features that have been merged in the last few months.

I added support for the LangVersion option to the MirrorSharpFsharpOptions as well, which enables people to use any of the features gated by specific language version/preview support: [feature list](https://github.com/dotnet/fsharp/blob/master/src/fsharp/LanguageFeatures.fs#L51-L67)

### CODE REVIEW

**Comment by baronfel** [comment]
I'm not sure how support for LangVersion would flow through sharplab specifically, though.

Another thing I noticed: it looks like in sharplab the F# support is using .Net Framework instead of .Net Core assemblies? If that's right I can help fix that.

**Comment by ashmind** [comment]
Thanks! Looks good -- I'll take a look soon.
I just caused some conflicts by updating master, but I should be able to resolve them.

For SharpLab:
1. `LangVersion` is normally set to the current maximum value -- I can set that
2. SharpLab has both .NET Core and .NET Framework sites depending on what you select in dropdown -- each one should use corresponding platform for F#?

**Comment by baronfel** [comment]
LangVersion should probably just be 'preview' for us, then. This includes all present and future language enhancements.Re .net core/.net  framework: there's a --targetprofile (I think?) command line setting that should vary based on that choice. It should be --targetprofile:netcore for .net core, and --targetprofile:mscorlib for .net framework. I'll get the correct value and update here.

**Comment by ashmind** [comment]
Thanks -- do you want to include `--targetprofile` in this PR? If so I'll not merge until that's added.

**Comment by baronfel** [comment]
I went ahead and added it. 

The valid values are (taken from the F# compiler codebase):
```fsharp
// Indicates we assume "mscorlib.dll", i.e .NET Framework, Mono and Profile 47
| "mscorlib" -> PrimaryAssembly.Mscorlib
// Indicates we assume "System.Runtime.dll", i.e .NET Standard 1.x, .NET Core App 1.x and above, and Profile 7/78/259
| "netcore"  -> PrimaryAssembly.System_Runtime
// Indicates we assume "netstandard.dll", i.e .NET Standard 2.0 and above
| "netstandard"  -> PrimaryAssembly.NetStandard
```

but all code in the compiler uses one of "mscorlib" or "netcore", so for SharpLab that seems a reasonable path to follow.

**Comment by ashmind** [comment]
I wonder if we want to provide string constants for those, but anyways can always add later.

**Comment by joelpryde** [comment]
Is there any way to set the TargetProfile for normal CSharp compilation?  I can't seem to find that option.

**Pull request merged**
