### PR TITLE
Add icon for extension methods in auto-complete list

### PR DESCRIPTION
**Pull request by johannesegger**

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks! I'll change to a separate icon since VS image pack has one.

**Comment by johannesegger** [comment]
Ok perfect, thanks. I also thought so, but then I checked in VSCode and there it has the same icon as a normal method.

**Comment by ashmind** [comment]
Publish is OK, mirrorsharp@0.9.5 should include the new icon.

**Comment by Sicos1977** [comment]
@johannesegger : Can you tell me how you show the extension methods?

I have a class with extension methods for another object but I don't see them in mirrorsharp. Is there some kind of special setting that I need todo?

**Comment by Sicos1977** [comment]
I have an extension method like this that adds a method to the Attachment obkect

```c#
    #region GetAllText
    /// <summary>
    ///     Retourneert alle tekst die aanwezig is in de <paramref name="attachment"/>
    /// </summary>
    /// <param name="attachment">De <paramref name="attachment"/></param>
    /// <param name="disableEmbeddedContent">Wanneer <c>true</c> dan wordt embedded content niet gelezen, bijvoorbeeld een bijlage in een e-mail</param>
    /// <param name="includeProperties">Wanneer <c>true</c> dan worden de meta-data properties van een document ook geretourneerd, bijvoorbeeld de summary properties van een Word document</param>
    /// <returns>Alle gevonden tekst</returns>
    public static string GetAllText(this Attachment attachment,
        bool disableEmbeddedContent = false,
        bool includeProperties = false)
    {
        WriteToAuditLogsDetails(AuditLogAction.RecognizingAllText, $"Bijlage '{attachment.FileName}'");

        var result = RecognitionClient.FileGetAllText(
            attachment.FileName,
            StreamToArray(attachment.FileData),
            disableEmbeddedContent,
            includeProperties);

        WriteToAuditLogsDetails(AuditLogAction.RecognizedAllText, $"Lengte {FileManager.GetFileSizeString(result.Length, CultureInfo.CurrentCulture)}");

        return result;
    }
    #endregion
```

But I don't see this extension method in the auto-complete list

image

**Comment by Sicos1977** [comment]
I have setup mirrorsharp from owin like this:

        try
        {
            var applicationSettings = Server.BusinessLogic.ApplicationSettings.Instance;
#if (DEBUG)
            var metadataReferences = applicationSettings.GetValuesAsStringList("Script editor", "MetadataReferences_VOP");
#else
            var metadataReferences = applicationSettings.GetValuesAsStringList("Script editor", "MetadataReferences");
#endif

```c#
            var mirrorSharpOptions = new MirrorSharpOptions
                {
                    SelfDebugEnabled = false,
                    IncludeExceptionDetails = true
                }
                .SetupCSharp(m =>
                {
                    m.MetadataReferences = m.MetadataReferences.Clear();
                    foreach (var metadataReference in metadataReferences)
                        m.AddMetadataReferencesFromFiles(metadataReference);
                });

            app.MapMirrorSharp("/mirrorsharp", mirrorSharpOptions,
                new MirrorSharpServices
                {
                    SetOptionsFromClient = new SetOptionsFromClientExtension(),
                    ExceptionLogger = new ExceptionLogger()
                }
            );
        }
        catch (Exception exception)
        {
            new Server.BusinessLogic.Logging.ErrorLogs().Insert(exception);
        }
```

metadataReferences is a list with assemblies and one of those has the extension method class in it.

**Pull request merged**
