### PR TITLE
F# 6 updates

### PR DESCRIPTION
**Pull request by Lanayx**
Support for new .NET 6 features of F# 6

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks for raising this! Seems like build was disabled on PRs -- enabled build and it highlighted some breaking changes to be resolved.

**Comment by baronfel** [comment]
@Lanayx if you have questions about the FileSystem API changes, feel free to ping me :)

**Comment by Lanayx** [comment]
I've fixed the build, @baronfel you are welcome to review

**Comment by ashmind** [comment]
Adjusted few minor things that were faster to adjust than to comment on -- will merge once build passes.

**Pull request merged**
