### PR TITLE
Update F# packages to their latest versions.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
This PR paves the way towards fixing https://github.com/ashmind/SharpLab/issues/348.

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks! Seems like there is some problem with the build?
```
FSharpProjectOptionsExtensionsTests.cs(95,24): error CS7036: There is no argument given that corresponds to the required formal parameter 'stamp' of 'FSharpProjectOptions.FSharpProjectOptions(string, FSharpOption<string>, string[], string[], Tuple<string, FSharpProjectOptions>[], bool, bool, DateTime, FSharpOption<UnresolvedReferencesSet>, FSharpList<Tuple<Range.range, string>>, FSharpOption<object>, FSharpOption<long>)' [C:\projects\mirrorsharp\Tests.Roslyn2.Net46\Tests.Roslyn2.Net46.csproj]
```

**Comment by teo-tsirpanis** [comment]
I fixed the _build_ error.

However, six unit tests fail. Given that this codebase is entirely foreign to me, I will need your help here.

**Comment by ashmind** [comment]
Thanks! I'll investigate, but can't promise a specific time at the moment.

**Comment by ashmind** [comment]
I've fixed some tests and you can ignore non-F# ones (flaky for now), the main remaining one is `TypeChar_ProducesExpectedCompletion`, which relates to the change here https://github.com/ashmind/mirrorsharp/pull/97/files#diff-e30a728fd87bc2645fedefaf23af8c1bR187.

I don't know the right parameters to `GetDeclarationListSymbols`, so please take a look at it if you have time, otherwise I might revisit and try to investigate, but might take a month or more.

**Comment by realvictorprm** [comment]
I think the F# package can already be updated to F# Core 4.6

**Comment by baronfel** [comment]
I've cloned this branch locally and have been able to green up the affected tests, the only change is in the `column` parameter of the `QuickParse.GetPartialLongNameEx` method. I think there might be a mixup between the compiler's internal line and column bookkeeping and MirrorSharp's, where the compiler wants the 0-based column and we're passing in the 1-based column.

Anyway, this single change fixes the tests:
`QuickParse.GetPartialLongNameEx(_text.Substring(info.line.Start, info.line.Length), info.column-1),`
.

There are also newer versions of FSharp.Core and FSharp.Compiler.Service.  This change works with those as well, though updating to the latest FSharp.Compiler.Service will cause you to have to bump your target framework from net46 to net461 at a minimum, which has ripple effects on other projects (Owin.Demo and the net46 tests at least).

Anyway, hope this helped!

**Comment by ashmind** [comment]
Thanks a lot! This seems to be it, I'll wait for tests to finish and then merge.
Might take a bit of time until I get it into SharpLab itself, but shouldn't be too long.

**Pull request merged**
